name: ğŸ› ï¸ Update README with Recent Repos

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write   # ğŸ”‘ Autorise les commits/push


jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run README Repos List
        uses: koj-co/readme-repos-list@v1.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "user:AmarzitMathias sort:updated" 
          max: 5
          path: README.md
          start: "<!--START_SECTION:repos-->"
          end: "<!--END_SECTION:repos-->"

      - name: âœ… Commit et push si modifications
  run: |
    git config --global user.name 'github-actions[bot]'
    git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    git add README.md
    git diff --cached --quiet || git commit -m "ğŸ“„ Update README with recent repositories"
    git pull --rebase origin main
    git push

